image:
  repository: byzanteam/jet_factory
  pullPolicy: IfNotPresent
  tag: "sha-9dbb6617274aa0c76779092a31cb5ab27e567bc0"

imageCredentials:
  registry: ghcr.io
  username: YkeLit
  password: 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
  email: dev@byzan.team

nameOverride: "jet-temp"
fullnameOverride: "jet-temp"

service:
  - name: jet-temp
    type: ClusterIP
    port: 4000

env:
  SECRET_KEY_BASE: OE4FgXJDHF2jA3VYfva522bKiDVKXyi2btZ1aMhbaK/kpOjCNc64ccixrADtcjsK
  PHX_HOST: "localhost"

jetHost: 10.163.1.104

traefik:
  - name: web
    path: /

initContainers:
  - name: "{{ .Chart.Name }}-create-database"
    image: postgres:9.5
    command:
      - /bin/sh
      - -c
      - |
        psql -c "SELECT 1" \
        "user=postgres password=123456 dbname=fact host=postgres" || \
        psql -c "CREATE DATABASE {{ fact }}" \
        "user=postgres password=123456 dbname=fact host=postgres"
  - name: "{{ .Chart.Name }}-migrate-sql"
    image: '{{ include "application-chart-template.image" $ }}'
    command:
      - /bin/sh
      - -c
      - /app/bin/db_migrate
    envFrom:
      - configMapRef:
          name: "{{ .Chart.Name }}-env"