{{ if .Values.appIngressroute | empty |not }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "application-chart-template.fullname" . }}-redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
