apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "application-chart-template.fullname" . }}-server-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
