{{- if .Values.jetTLSSecret | empty | not }}
{{- with .Values.jetTLSSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-tls-secret
  labels:
    {{ include "application-chart-template.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "Please provide `certificate` for appTLSSecret" .certificate | nindent 4 }}
  tls.key: {{ required "Please provide `key` for appTLSSecret" .key | nindent 4 }}
{{- end }}
{{- end }}
