apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-chart-template.fullname" . }}
  labels:
    {{- include "application-chart-template.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "application-chart-template.selectorLabels" $ | nindent 4 }}
---
{{- if .Values.externalEndPoint | empty | not }}
{{- range .Values.externalEndPoint }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-{{ .name }}
  labels:
    {{- include "application-chart-template.labels" $ | nindent 4 }}
subsets:
- addresses:
  - ip: {{ .ip }}
  ports:
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
{{- end }}
{{- end }}
---
{{- if .Values.externalService | empty | not }}
{{- range .Values.externalService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-chart-template.fullname" $ }}-{{ .name }}
  labels:
    {{- include "application-chart-template.labels" $ | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  selector:
    {{- include "application-chart-template.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
